my-app:
  process-instances: ${PROCESS_INSTANCES:100}
  process-id: ${PROCESS_ID:benchmark}

camunda:
  client:
    mode: self-managed
    grpc-address: ${GRPC_ADDRESS:http://localhost:26500}
    rest-address: ${REST_ADDRESS:http://localhost:8088}
    prefer-rest-over-grpc: false
    auth:
      method: none

spring:
  main:
    banner-mode: off

logging:
  level:
    de.envite.event: ${LOGGING_LEVEL_APP:info}
    root: ${LOGGING_LEVEL_ROOT:info}

