process-instances: ${PROCESS_INSTANCES:100}

camunda:
  client:
    mode: self-managed
    grpc-address: ${GRPC_ADDRESS:http://localhost:26500}
    rest-address: ${REST_ADDRESS:http://localhost:8088}
    worker:
      defaults:
        stream-enabled: true
        request-timeout: PT0.5S
      #request-timeout: PT0.1S
