mo:
  may-fancy-namespace:
    my-vlue: ${AFFENTANZ}

camunda:
  client:
    mode: self-managed
    grpc-address: http://orchestration:26500
    rest-address: http://orchestration:8080
    worker:
      defaults:
        stream-enabled: true
        request-timeout: PT0.5S
      #request-timeout: PT0.1S
