#mo:
#  may-fancy-namespace:
#    my-vlue: ${AFFENTANZ}

experiment:
  process-instances:
    amount: ${PROCESS_INSTANCES:100}
  process-name: ${PROCESS_NAME:C8_benchmark}


logging:
  level:
    root: off